In [33]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd


In [34]:
iris=load_iris()

In [35]:
# Logistic Regression

In [36]:
l_scores=cross_val_score(LogisticRegression( max_iter=150),iris.data,iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [37]:
np.average(l_scores)

0.9733333333333334

In [38]:
# Decision Tree

In [39]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [40]:
np.average(d_scores)

0.9666666666666668

In [28]:
# Support Vector Machine

In [41]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [42]:
np.average(s_scores)

0.9666666666666666

In [43]:
# Random Forest Classifier

In [53]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=10), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [55]:
np.average(r_scores)

0.9666666666666668